[web]
web-server ansible_host=13.221.133.167

[app]
app-server ansible_host=34.229.129.120

[db]
db-server ansible_host=98.89.43.16

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=./demoKeyPair.pem
